# Generated by Django 4.2.7 on 2025-10-27 00:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('consumption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumptionreading',
            name='production_kwh',
            field=models.FloatField(default=0.0, help_text='Produção de energia em kWh no momento da leitura', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Produção (kWh)'),
        ),
        migrations.CreateModel(
            name='EnergyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora da leitura', verbose_name='Data e Hora')),
                ('production_kwh', models.FloatField(help_text='Produção de energia em kWh no momento da leitura', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Produção (kWh)')),
                ('power_watts', models.FloatField(blank=True, help_text='Potência de produção em Watts no momento da leitura', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Potência (W)')),
                ('solar_irradiance', models.FloatField(blank=True, help_text='Irradiância solar em W/m²', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Irradiância Solar (W/m²)')),
                ('temperature', models.FloatField(blank=True, help_text='Temperatura ambiente em Celsius', null=True, verbose_name='Temperatura (°C)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_readings', to='devices.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Leitura de Produção',
                'verbose_name_plural': 'Leituras de Produção',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['device', 'timestamp'], name='consumption_device__c97f4b_idx'), models.Index(fields=['timestamp'], name='consumption_timesta_c75896_idx')],
            },
        ),
    ]
