# Generated by Django 4.2.7 on 2025-10-27 01:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumption', '0002_consumptionreading_production_kwh_energyproduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome amigável para o inversor solar', max_length=100, verbose_name='Nome do Inversor')),
                ('panel_id', models.CharField(help_text='Identificador único do inversor solar', max_length=100, unique=True, verbose_name='ID do Inversor')),
                ('nominal_power_kwp', models.FloatField(help_text='Potência nominal do inversor em kWp', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Potência Nominal (kWp)')),
                ('is_active', models.BooleanField(default=True, help_text='Se o inversor está ativo e sendo monitorado', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_solar_panels', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Inversor Solar',
                'verbose_name_plural': 'Inversores Solares',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['panel_id'], name='consumption_panel_i_e2e631_idx'), models.Index(fields=['is_active'], name='consumption_is_acti_9b1e2e_idx')],
            },
        ),
    ]
