# Generated by Django 4.2.7 on 2025-10-27 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('consumption', '0003_solarpanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyproduction',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Dispositivo associado (opcional para painéis solares)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_readings', to='devices.device', verbose_name='Dispositivo'),
        ),
    ]
