# Generated by Django 4.2.7 on 2025-10-27 01:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumption', '0004_alter_energyproduction_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumptionalert',
            name='alert_type',
            field=models.CharField(choices=[('high_consumption', 'Consumo Alto'), ('limit_exceeded', 'Limite Excedido'), ('device_offline', 'Dispositivo Offline'), ('unusual_pattern', 'Padrão Incomum'), ('device_auto_controlled', 'Dispositivo Controlado Automaticamente'), ('medium_priority_action_needed', 'Ação Necessária - Prioridade Média'), ('deficit_detected', 'Déficit de Produção Detectado')], max_length=30, verbose_name='Tipo de Alerta'),
        ),
        migrations.CreateModel(
            name='EnergyManagementConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome descritivo para a configuração', max_length=100, verbose_name='Nome da Configuração')),
                ('deficit_threshold_percentage', models.FloatField(default=100.0, help_text='Percentual mínimo de produção em relação ao consumo para evitar controle automático', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(500.0)], verbose_name='Limiar de Déficit (%)')),
                ('auto_control_enabled', models.BooleanField(default=True, help_text='Se o controle automático de dispositivos está habilitado', verbose_name='Controle Automático Ativo')),
                ('is_active', models.BooleanField(default=True, help_text='Se esta é a configuração ativa (apenas uma pode estar ativa)', verbose_name='Configuração Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_energy_configs', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Configuração de Gerenciamento de Energia',
                'verbose_name_plural': 'Configurações de Gerenciamento de Energia',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='consumption_is_acti_7d0d00_idx'), models.Index(fields=['auto_control_enabled'], name='consumption_auto_co_4df01d_idx')],
            },
        ),
    ]
