# Generated by Django 4.2.7 on 2025-10-26 23:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome amigável para o dispositivo', max_length=100, verbose_name='Nome do Dispositivo')),
                ('device_id', models.CharField(help_text='Identificador único do dispositivo', max_length=100, unique=True, verbose_name='ID do Dispositivo')),
                ('device_type', models.CharField(choices=[('manual', 'Manual'), ('tuya', 'Tuya'), ('smart', 'Smart')], default='manual', max_length=10, verbose_name='Tipo do Dispositivo')),
                ('tuya_ip', models.GenericIPAddressField(blank=True, help_text='Endereço IP local do dispositivo Tuya', null=True, verbose_name='IP Local (Tuya)')),
                ('tuya_local_key', models.CharField(blank=True, help_text='Chave local para comunicação com dispositivo Tuya', max_length=100, null=True, verbose_name='Chave Local (Tuya)')),
                ('tuya_version', models.DecimalField(decimal_places=1, default=3.3, help_text='Versão do protocolo Tuya', max_digits=3, validators=[django.core.validators.MinValueValidator(3.0), django.core.validators.MaxValueValidator(3.4)], verbose_name='Versão Tuya')),
                ('last_consumption', models.FloatField(default=0.0, help_text='Último consumo registrado em kWh', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Último Consumo (kWh)')),
                ('max_consumption', models.FloatField(default=10.0, help_text='Consumo máximo esperado em kWh', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Consumo Máximo (kWh)')),
                ('is_active', models.BooleanField(default=True, help_text='Se o dispositivo está ativo e sendo monitorado', verbose_name='Ativo')),
                ('is_controllable', models.BooleanField(default=False, help_text='Se o dispositivo pode ser controlado remotamente', verbose_name='Controlável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_devices', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Dispositivo',
                'verbose_name_plural': 'Dispositivos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, help_text='Se o dispositivo está online', verbose_name='Online')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Última vez que o dispositivo foi visto online', null=True, verbose_name='Última Conexão')),
                ('current_power', models.FloatField(default=0.0, help_text='Potência atual em Watts', validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Potência Atual (W)')),
                ('voltage', models.FloatField(blank=True, help_text='Voltagem atual em Volts', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Voltagem (V)')),
                ('current_amperage', models.FloatField(blank=True, help_text='Corrente atual em Amperes', null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Corrente (A)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='devices.device', verbose_name='Dispositivo')),
            ],
            options={
                'verbose_name': 'Status do Dispositivo',
                'verbose_name_plural': 'Status dos Dispositivos',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_id'], name='devices_dev_device__e2c19e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['device_type'], name='devices_dev_device__0d8d82_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['is_active'], name='devices_dev_is_acti_52b321_idx'),
        ),
    ]
