# Generated by Django 4.2.7 on 2025-10-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auto_control_timestamp',
            field=models.DateTimeField(blank=True, help_text='Data e hora do último controle automático', null=True, verbose_name='Data do Controle Automático'),
        ),
        migrations.AddField(
            model_name='device',
            name='auto_controlled',
            field=models.BooleanField(default=False, help_text='Se o dispositivo foi controlado automaticamente pelo sistema', verbose_name='Controlado Automaticamente'),
        ),
        migrations.AddField(
            model_name='device',
            name='priority',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Média'), ('baixa', 'Baixa')], default='alta', help_text='Prioridade do dispositivo para controle automático', max_length=10, verbose_name='Prioridade'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['priority'], name='devices_dev_priorit_1acf89_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['auto_controlled'], name='devices_dev_auto_co_6e74e5_idx'),
        ),
    ]
